"""macOS path-with-spaces workaround for FEMMT.

FEMMT 0.5.x calls ``getdp`` via shell strings that don't quote the
package path. When the venv is inside something like
``~/Documents/02 - Trabalho/indutor/.venv``, the space breaks the call
and gmsh receives a truncated argument like ``/Users/.../02.pro``.

The workaround is to symlink the FEMMT package into a no-spaces path
(``/tmp/femmt`` is fine — it's regenerated by the kernel on boot when
the symlink target survives) and prepend that to ``sys.path`` before
``import femmt`` happens.
"""

from __future__ import annotations

import os
import sys
from pathlib import Path
from typing import Optional

SHIM_DIR = Path("/tmp/pfc_femmt_shim")


def _femmt_path() -> Optional[Path]:
    try:
        import femmt  # type: ignore[import-not-found]
    except ImportError:
        return None
    init = getattr(femmt, "__file__", None)
    return Path(init).resolve() if init else None


def needs_workaround() -> bool:
    """True iff the active FEMMT install lives under a path with spaces."""
    p = _femmt_path()
    return p is not None and " " in str(p)


def install_path_workaround(*, force: bool = False) -> Optional[Path]:
    """Create the no-spaces shim directory and patch ``sys.path``.

    Returns the shim path on success, ``None`` if no workaround was
    needed (or if FEMMT isn't installed yet).
    """
    if not force and not needs_workaround():
        return None
    real_init = _femmt_path()
    if real_init is None:
        return None
    real = real_init.parent
    SHIM_DIR.mkdir(parents=True, exist_ok=True)
    target = SHIM_DIR / "femmt"
    if target.is_symlink() or target.exists():
        try:
            if target.is_symlink():
                target.unlink()
            elif target.is_dir():
                # Only delete if empty — refuse to nuke a real install.
                target.rmdir()
        except OSError:
            return SHIM_DIR  # already there
    try:
        os.symlink(str(real), str(target), target_is_directory=True)
    except OSError:
        return None
    if str(SHIM_DIR) not in sys.path:
        sys.path.insert(0, str(SHIM_DIR))
    return SHIM_DIR
