"""Generate FEMM Lua scripts for inductor validation problems.

Currently supports:
- Toroidal axisymmetric magnetostatic (the workhorse for PFC chokes).

The generated script:
1. Creates a magnetostatic 2D-axisymmetric problem in millimetres
2. Defines linear materials (Air, Copper, "CoreMat") using the small-signal
   permeability of the core material at the operating DC bias point. For
   nonlinear cores we register a B-H lookup if the rolloff curve is provided
3. Builds the geometry (core cross-section, winding cross-section, far-field box)
4. Excites the coil with a circuit current `I_pk · N` (turns × peak amps)
5. Solves and writes a key-value results file we can parse without FEMM linking

The resulting Lua script is pure text and is unit-tested as text — it does
not need to execute to verify it's well-formed.
"""
from __future__ import annotations
import math
from dataclasses import dataclass
from pathlib import Path

from pfc_inductor.models import Core, Material
from pfc_inductor.physics.rolloff import mu_pct
from pfc_inductor.visual.core_3d import infer_shape, _toroid_dims


@dataclass
class FEAJobInputs:
    core: Core
    material: Material
    N_turns: int
    I_pk_A: float
    output_dir: Path
    job_name: str = "pfc_validation"

    @property
    def fem_path(self) -> Path:
        return self.output_dir / f"{self.job_name}.fem"

    @property
    def lua_path(self) -> Path:
        return self.output_dir / f"{self.job_name}.lua"

    @property
    def results_path(self) -> Path:
        return self.output_dir / f"{self.job_name}.results.txt"


def _operating_mu_eff(material: Material, H_Oe: float) -> float:
    """Effective relative permeability at operating DC bias H."""
    return material.mu_initial * mu_pct(material, H_Oe)


def _toroid_lua(inputs: FEAJobInputs) -> str:
    """Lua source for an axisymmetric toroidal core + concentrated winding.

    Geometry in mm (axi-r is "x", axi-z is "y"):
      - Core rectangle: r ∈ [ID/2, OD/2], z ∈ [-HT/2, +HT/2]
      - Winding rectangle: surrounds the core with a small clearance
      - Far field square boundary
    """
    core = inputs.core
    material = inputs.material
    N = inputs.N_turns
    I_pk = inputs.I_pk_A

    dims = _toroid_dims(core)
    if dims is None:
        raise ValueError("Toroid dimensions could not be derived from core data")
    OD, ID, HT = dims

    R_in = ID / 2.0
    R_out = OD / 2.0
    z_top = HT / 2.0
    z_bot = -HT / 2.0
    clearance = max(min(HT, OD - ID) * 0.15, 0.5)
    wr_in = max(R_in - clearance, 0.5)
    wr_out = R_out + clearance
    wz_top = z_top + clearance
    wz_bot = z_bot - clearance

    # Far-field box. 4× the core OD is plenty for axi domain truncation.
    far = max(OD * 4.0, HT * 4.0)

    # Operating-point H to set the linear permeability used by FEMM
    # (matches our small-signal value at I_pk).
    le_m = core.le_mm * 1e-3
    H_Am = N * I_pk / max(le_m, 1e-9)
    H_Oe = H_Am / 79.5774715459
    mu_eff = _operating_mu_eff(material, H_Oe)

    # Sigma for the core material: powders are insulating-ish at fsw
    # frequencies; ferrites have very low conductivity. Use 0 unless we
    # explicitly model eddy currents.
    sigma_core = 0.0

    return f"""\
-- Auto-generated by pfc_inductor.fea.geometry
-- Job: {inputs.job_name}
-- Core: {core.vendor} {core.part_number} ({core.shape})
-- Material: {material.vendor} {material.name}  mu_initial={material.mu_initial}
-- Operating point: I_pk = {I_pk:.3f} A, N = {N}, H = {H_Oe:.1f} Oe, mu_eff = {mu_eff:.1f}

newdocument(0)  -- 0 = magnetics
mi_probdef(0, "millimeters", "axi", 1.e-8, 0, 30, 0)

-- Materials
mi_addmaterial("Air",     1, 1, 0, 0, 0,         0, 0, 1, 0, 0, 0)
mi_addmaterial("Copper",  1, 1, 0, 0, 58,        0, 0, 1, 0, 0, 0)
mi_addmaterial("CoreMat", {mu_eff:.4f}, {mu_eff:.4f}, 0, 0, {sigma_core},   0, 0, 1, 0, 0, 0)

-- Boundary (Dirichlet A = 0 on far field)
mi_addboundprop("Outer", 0, 0, 0, 0, 0, 0, 0, 0, 0)

-- Circuit
mi_addcircprop("Coil", {I_pk:.6f}, 1)

-- ---- Core geometry (rectangle in r-z plane) ----
mi_addnode({R_in:.4f}, {z_bot:.4f})
mi_addnode({R_out:.4f}, {z_bot:.4f})
mi_addnode({R_out:.4f}, {z_top:.4f})
mi_addnode({R_in:.4f}, {z_top:.4f})
mi_addsegment({R_in:.4f}, {z_bot:.4f}, {R_out:.4f}, {z_bot:.4f})
mi_addsegment({R_out:.4f}, {z_bot:.4f}, {R_out:.4f}, {z_top:.4f})
mi_addsegment({R_out:.4f}, {z_top:.4f}, {R_in:.4f}, {z_top:.4f})
mi_addsegment({R_in:.4f}, {z_top:.4f}, {R_in:.4f}, {z_bot:.4f})

-- Core block label
mi_addblocklabel({(R_in + R_out) / 2:.4f}, 0)
mi_selectlabel({(R_in + R_out) / 2:.4f}, 0)
mi_setblockprop("CoreMat", 1, 0, "<None>", 0, 1, 0)
mi_clearselected()

-- ---- Winding wraps both sides of the core (top-of-toroid view).
-- We model a single annular region surrounding the core with the total
-- circuit current; FEMM's circuit handles the N·I assignment.
mi_addnode({wr_in:.4f}, {wz_bot:.4f})
mi_addnode({wr_out:.4f}, {wz_bot:.4f})
mi_addnode({wr_out:.4f}, {wz_top:.4f})
mi_addnode({wr_in:.4f}, {wz_top:.4f})
mi_addsegment({wr_in:.4f}, {wz_bot:.4f}, {wr_out:.4f}, {wz_bot:.4f})
mi_addsegment({wr_out:.4f}, {wz_bot:.4f}, {wr_out:.4f}, {wz_top:.4f})
mi_addsegment({wr_out:.4f}, {wz_top:.4f}, {wr_in:.4f}, {wz_top:.4f})
mi_addsegment({wr_in:.4f}, {wz_top:.4f}, {wr_in:.4f}, {wz_bot:.4f})

-- Winding block label (between core outer wall and winding outer wall).
mi_addblocklabel({(R_out + wr_out) / 2:.4f}, 0)
mi_selectlabel({(R_out + wr_out) / 2:.4f}, 0)
mi_setblockprop("Copper", 1, 0, "Coil", 0, 2, {N})
mi_clearselected()

-- ---- Far-field box (axi: r >= 0 only) ----
mi_addnode(0, {-far:.4f})
mi_addnode({far:.4f}, {-far:.4f})
mi_addnode({far:.4f}, {far:.4f})
mi_addnode(0, {far:.4f})
mi_addsegment(0, {-far:.4f}, {far:.4f}, {-far:.4f})
mi_addsegment({far:.4f}, {-far:.4f}, {far:.4f}, {far:.4f})
mi_addsegment({far:.4f}, {far:.4f}, 0, {far:.4f})
mi_addsegment(0, {far:.4f}, 0, {-far:.4f})

-- Air block label (anywhere outside the windings/core).
mi_addblocklabel({far * 0.6:.4f}, {far * 0.4:.4f})
mi_selectlabel({far * 0.6:.4f}, {far * 0.4:.4f})
mi_setblockprop("Air", 1, 0, "<None>", 0, 0, 0)
mi_clearselected()

-- Apply boundary on the outer arc/rect.
mi_selectsegment({far:.4f}, 0)
mi_selectsegment({far / 2:.4f}, {-far:.4f})
mi_selectsegment({far / 2:.4f}, {far:.4f})
mi_setsegmentprop("Outer", 0, 0, 0, 0)
mi_clearselected()

-- ---- Solve ----
mi_zoomnatural()
mi_saveas("{inputs.fem_path.as_posix()}")
mi_analyze(1)
mi_loadsolution()

-- Extract circuit values: I, V, Flux_linkage  (mo_getcircuitproperties)
local I_circuit, V_circuit, FluxLinkage = mo_getcircuitproperties("Coil")
local L_H = 0
if math.abs(I_circuit) > 1e-12 then
    L_H = FluxLinkage / I_circuit
end

-- Peak |B| in the core: sample a grid inside the core rectangle.
local Bmax = 0
local n_r = 25
local n_z = 25
local r_step = ({R_out:.4f} - {R_in:.4f}) / n_r
local z_step = ({z_top:.4f} - {z_bot:.4f}) / n_z
for ir = 0, n_r do
    for iz = 0, n_z do
        local r = {R_in:.4f} + ir * r_step
        local z = {z_bot:.4f} + iz * z_step
        local Br, Bz = mo_getb(r, z)
        local Bmag = math.sqrt(Br*Br + Bz*Bz)
        if Bmag > Bmax then Bmax = Bmag end
    end
end

-- Write key=value results.
local f = io.open("{inputs.results_path.as_posix()}", "w")
f:write(string.format("L_H=%.10e\\n", L_H))
f:write(string.format("flux_linkage_Wb=%.10e\\n", FluxLinkage))
f:write(string.format("I_test_A=%.10e\\n", I_circuit))
f:write(string.format("V_circuit_V=%.10e\\n", V_circuit))
f:write(string.format("B_pk_T=%.10e\\n", Bmax))
f:write(string.format("mu_eff_used=%.6f\\n", {mu_eff:.6f}))
f:write(string.format("N_turns=%d\\n", {N}))
f:close()

mi_close()
"""


def build_lua_script(inputs: FEAJobInputs) -> str:
    """Dispatch by core shape. For now only toroid axisymmetric is supported."""
    kind = infer_shape(inputs.core)
    if kind == "toroid":
        return _toroid_lua(inputs)
    raise NotImplementedError(
        f"FEA validation for shape {kind!r} not implemented yet "
        "(only toroidal axisymmetric is in v1)."
    )


def write_lua_script(inputs: FEAJobInputs) -> Path:
    """Generate the Lua script and write it to inputs.lua_path. Returns the path."""
    inputs.output_dir.mkdir(parents=True, exist_ok=True)
    script = build_lua_script(inputs)
    inputs.lua_path.write_text(script, encoding="utf-8")
    return inputs.lua_path
