"""AC harmonic (MagDyn) ``.pro`` template — Phase 2.1 of the FEA replacement.

This complements the DC ``magnetostatic_axi`` template with a
frequency-domain solve for skin / proximity loss extraction. The
formulation matches FEMMT's ``MagDyn_a`` (frequency-domain
magneto-dynamic vector-potential formulation) so the validated
GetDP construct stays the same; we just rebuild the ``.pro``
under our region-tagging convention.

Physics summary
===============

In the frequency domain (single excitation frequency ``f``) the
vector-potential ``A(r,z,t) = Re[ A_phasor(r,z) · exp(jωt) ]``
satisfies::

    ∇ × (ν · ∇ × A)  +  jω · σ · A  =  J_source

where ``ω = 2π·f`` and ``σ`` is the local conductivity (non-zero
in copper windings, zero in air / ferrite / powder). The
imaginary part of the input impedance gives the AC inductance:

::

    Z = R_ac + jω·L_ac
    L_ac = Im(Z) / ω
    R_ac = Re(Z)

Loss extraction
===============

For sinusoidal steady state:

- **Joule heating in solid conductors**::

      P_cu = ½ · ∫_DomainC  σ · |jω·A + ∇U|²  dΩ

  In the simplified single-conductor model below we use
  ``∇U = U / depth`` to drive the current; FEMMT's circuit
  constraints implement the full coupled-impedance system but
  produce the same scalar result for a single winding.

- **Core hysteresis losses** are NOT captured here (the
  ``MagDyn_a`` formulation only models eddy currents in the iron
  via ``σ_core``). For PFC ferrites we set ``σ_core = 0`` and
  derive hysteresis from the Steinmetz fit downstream.

Differences from FEMMT
======================

We omit:

- Stranded / Litz function spaces (Phase 2.3).
- Foil winding modelling (Phase 2.4).
- Time-domain (transient) variant — Phase 4.1.
- Coupled circuit equations — the single-winding inductor case
  doesn't need them; the imprinted current density approach is
  cleaner and matches the analytical engine's drive.

We keep:

- ``Hcurl_a_2D`` function space (BF_PerpendicularEdge for axi).
- ``VolAxiSqu`` jacobian (axisymmetric integration).
- ``-jω·σ·A`` eddy-current term.
- Frequency-domain Resolution operator.
- Postprocessing for B field, joule loss density, total power.

Where they differ
=================

- Region tags use our ``RegionTag`` enum, not FEMMT's
  ``Iron / Air / Winding_1`` names.
- Single solid conductor (no per-strand subdivision).
- Voltage constraint computed from prescribed current via the
  scalar impedance update (``U = jω·L_dc·I`` as initial guess,
  solved self-consistently by GetDP).
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional

from pfc_inductor.fea.direct.geometry.base import RegionTag


@dataclass(frozen=True)
class MagnetostaticAcInputs:
    """Inputs for the AC harmonic template.

    Same field shape as :class:`MagnetostaticInputs` plus the
    frequency and conductivity entries needed for the eddy-current
    term.
    """

    mu_r_core: float
    """Relative permeability of the core material."""

    sigma_core_Spm: float = 0.0
    """Core conductivity (S/m). 0 for ferrite (no core eddy currents
    in the FEM — Steinmetz fit handles hysteresis separately).
    Non-zero for silicon-steel laminations (Phase 2.2)."""

    sigma_copper_Spm: float = 5.96e7
    """Copper electrical conductivity (S/m) at 20 °C. IACS
    standard 5.96e7 unless overridden. For higher-temperature
    operating points this rolls off ~0.4 %/K; the cascade may
    update this from the thermal pass."""

    n_turns: int = 1
    current_A: float = 1.0
    """Peak coil current (A). Note: phasor amplitude. The user
    typically passes ``I_pk`` (peak value, not RMS); the formulation
    is linear so the choice scales all field amplitudes."""

    coil_area_m2: float = 1e-4
    """One-bundle cross-section area × (2π·R_mean) for axi —
    same convention as DC."""

    frequency_Hz: float = 130_000.0
    """Excitation frequency (Hz). Typical PFC switchers are
    50–500 kHz. The output ``L_ac`` is normally only weakly
    frequency-dependent below the first winding resonance;
    ``R_ac`` rises ~√f from skin effect."""


class MagnetostaticAcTemplate:
    """Render a GetDP ``.pro`` for the AC harmonic problem.

    Usage mirrors :class:`MagnetostaticAxiTemplate`. The runner
    layer calls this for the AC pass once the DC pass has supplied
    a starting field configuration; for now the AC solve is
    independent (no warm start) — that's a Phase 2.6 optimisation.
    """

    _TEMPLATE = r"""// Auto-generated by pfc_inductor.fea.direct.physics.magnetostatic_ac
// AC harmonic (MagDyn_a) — frequency-domain A_φ for axisymmetric inductors
// Phase 2.1 of the FEMMT-replacement effort.

Group {{
  Core       = Region[{core_tag}];
  AirGap     = Region[{air_gap_tag}];
  Air        = Region[{air_outer_tag}];
  Coil_pos   = Region[{coil_pos_tag}];
  OuterBound = Region[{outer_boundary_tag}];

  Magnetic   = Region[ {{Core, AirGap, Air, Coil_pos}} ];
  // Conductive sub-region — only copper carries eddy currents
  // in this simplified model. Ferrite + powder cores are treated
  // as σ=0 (hysteresis from Steinmetz downstream).
  DomainC    = Region[ {{Coil_pos}} ];
  DomainS    = Region[ {{Coil_pos}} ];   // source region (imprinted Js)
  Source     = Region[ {{Coil_pos}} ];
  NonSource  = Region[ {{Core, AirGap, Air}} ];
}}

Function {{
  mu0       = 4 * Pi * 1e-7;
  mu_r_core = {mu_r_core};
  mu[Core]    = mu0 * mu_r_core;
  mu[AirGap]  = mu0;
  mu[Air]     = mu0;
  mu[Coil_pos] = mu0;
  nu[]        = 1 / mu[];

  // Conductivity — only copper. Core σ kept as a placeholder for
  // future silicon-steel laminations.
  sigma[Core]       = {sigma_core_Spm};
  sigma[AirGap]     = 0;
  sigma[Air]        = 0;
  sigma[Coil_pos]   = {sigma_copper_Spm};

  // Frequency / angular frequency
  Freq      = {frequency_Hz};
  omega     = 2 * Pi * Freq;

  // Source current density (phasor amplitude). The same A_coil
  // we use in DC, since the axisymmetric geometry's 2π·R_mean
  // correction is identical.
  N_turns   = {n_turns};
  I_pk      = {current_A};
  A_coil    = {coil_area_m2};
  J_amp     = N_turns * I_pk / A_coil;
  js[Coil_pos] = Vector[ 0, 0, J_amp ];
}}

Constraint {{
  {{ Name MagDirichlet; Type Assign;
     Case {{ {{ Region OuterBound; Value 0.; }} }}
  }}
}}

Jacobian {{
  {{ Name JVol; Case {{ {{ Region All; Jacobian VolAxiSqu; }} }} }}
  {{ Name JSur; Case {{ {{ Region All; Jacobian SurAxi; }} }} }}
}}

Integration {{
  {{ Name I_Gauss;
     Case {{
       {{ Type Gauss;
          Case {{
            {{ GeoElement Triangle;   NumberOfPoints 4; }}
            {{ GeoElement Quadrangle; NumberOfPoints 4; }}
            {{ GeoElement Line;       NumberOfPoints 4; }}
          }}
       }}
     }}
  }}
}}

FunctionSpace {{
  {{ Name Hcurl_a; Type Form1P;
     BasisFunction {{
       {{ Name se; NameOfCoef ae; Function BF_PerpendicularEdge;
          Support Magnetic; Entity NodesOf[ All ]; }}
     }}
     Constraint {{
       {{ NameOfCoef ae; EntityType NodesOf;
          NameOfConstraint MagDirichlet; }}
     }}
  }}
}}

Formulation {{
  // MagDyn_a — vector-potential magneto-dynamic. Without circuit
  // constraints (no GlobalQuantity coupling), we drive the system
  // entirely via the imprinted current density js[]. The eddy-
  // current term σ·∂A/∂t adds the AC contribution; in frequency
  // domain this becomes jω·σ·A (handled by GetDP via ``DtDof``).
  {{ Name MagDyn_a; Type FemEquation;
     Quantity {{
       {{ Name a; Type Local; NameOfSpace Hcurl_a; }}
     }}
     Equation {{
       // Curl-curl
       Galerkin {{ [ nu[] * Dof{{d a}} , {{d a}} ];
         In Magnetic; Jacobian JVol; Integration I_Gauss; }}
       // Eddy current (frequency-domain: ∂t → jω)
       Galerkin {{ DtDof [ sigma[] * Dof{{a}} , {{a}} ];
         In DomainC; Jacobian JVol; Integration I_Gauss; }}
       // Imprinted source (− because the weak form has − ∫ js · δa)
       Galerkin {{ [ -js[] , {{a}} ];
         In Coil_pos; Jacobian JVol; Integration I_Gauss; }}
     }}
  }}
}}

Resolution {{
  {{ Name MagDyn;
     System {{
       {{ Name Sys_MagDyn;
          NameOfFormulation MagDyn_a;
          Type Complex;
          Frequency Freq;
       }}
     }}
     Operation {{ Generate[Sys_MagDyn]; Solve[Sys_MagDyn]; SaveSolution[Sys_MagDyn]; }}
  }}
}}

PostProcessing {{
  {{ Name MagDyn_post; NameOfFormulation MagDyn_a;
     Quantity {{
       {{ Name a;    Value {{ Local {{ [ {{a}} ];           In Magnetic;   Jacobian JVol; }} }} }}
       {{ Name b;    Value {{ Local {{ [ {{d a}} ];         In Magnetic;   Jacobian JVol; }} }} }}
       {{ Name nrm_b; Value {{ Local {{ [ Norm[{{d a}}] ];   In Magnetic;   Jacobian JVol; }} }} }}

       // Eddy-current loss density (real-power per volume).
       // In frequency domain: P = ½ · Re(σ · E · E*) where E = -jω·A
       // and so |E|² = ω² · |A|² ⟹ P = ½·σ·ω²·|A|²
       // For a steady-state phasor with peak amplitude scaling,
       // the time-averaged power follows ½·σ·ω²·|A|². The Norm[]
       // squared inside GetDP gives |A|² for the complex A.
       {{ Name P_density_cu;
          Value {{ Local {{ [ 0.5 * sigma[] * omega^2 * SquNorm[{{a}}] ];
            In DomainC; Jacobian JVol; }} }} }}

       // Magnetic energy density (real part)
       {{ Name w_mag;
          Value {{ Local {{ [ 0.5 * nu[] * SquNorm[{{d a}}] ];
            In Magnetic; Jacobian JVol; }} }} }}

       // Volume-integrated quantities — VolAxiSqu already includes
       // the 2π·r factor so these come out in Watts and Joules
       // directly.
       //
       // Note on the factor convention: with A as a complex
       // phasor amplitude (peak value, not RMS), the time-averaged
       // power dissipation is ½·σ·ω²·|A|² per volume; the energy
       // density is ¼·|B|²/μ. The 0.5 in P_cu is the time-average
       // factor; the energy uses 0.5 here so that the
       // ``L_from_W = 4·W/I_pk²`` formula in postproc recovers
       // the peak-energy convention (matches DC backend output).
       {{ Name P_cu;
          Value {{ Integral {{ [ 0.5 * sigma[] * omega^2 * SquNorm[{{a}}] ];
            In DomainC; Jacobian JVol; Integration I_Gauss; }} }} }}
       {{ Name W_mag;
          Value {{ Integral {{ [ 0.5 * nu[] * SquNorm[{{d a}}] ];
            In Magnetic; Jacobian JVol; Integration I_Gauss; }} }} }}

       // Flux-linkage method for L_ac (same approach as DC).
       // For the coil bundle with N turns spread over A_coil m²:
       //   Φ = ∫_Coil A_φ × (2π·r) / A_coil dA
       //   L = Φ × N / I
       // VolAxiSqu's 2π·r is baked into the integration, so
       // ``Integral [ CompZ[a] / A_coil ]`` returns Φ directly.
       // Per-turn flux × N gives total linkage; dividing by I
       // gives L. For complex A this is itself complex; the real
       // part is L_ac, the imaginary part divided by ω is the
       // contribution to R_ac.
       {{ Name FluxOverI;
          Value {{ Integral {{ [ CompZ[{{a}}] / A_coil / I_pk ];
            In Coil_pos; Jacobian JVol; Integration I_Gauss; }} }} }}
     }}
  }}
}}

PostOperation {{
  {{ Name MagDyn_out; NameOfPostProcessing MagDyn_post;
     Operation {{
       Print[ b,           OnElementsOf Magnetic, File "B_field_ac.pos" ];
       Print[ nrm_b,       OnElementsOf Magnetic, File "Magb_ac.pos" ];
       Print[ P_density_cu, OnElementsOf DomainC,  File "loss_density_cu.pos" ];
       Print[ a,           OnElementsOf Magnetic, File "A_potential_ac.pos" ];

       Print[ P_cu[DomainC],     OnGlobal, Format Table, File "p_cu_ac.txt" ];
       Print[ W_mag[Magnetic],   OnGlobal, Format Table, File "energy_ac.txt" ];
       Print[ FluxOverI[Coil_pos], OnGlobal, Format Table,
              File "flux_linkage_over_I_ac.txt" ];
     }}
  }}
}}
"""

    def render(self, inputs: MagnetostaticAcInputs) -> str:
        """Substitute ``inputs`` into the AC template."""
        return self._TEMPLATE.format(
            core_tag=RegionTag.CORE,
            air_gap_tag=RegionTag.AIR_GAP,
            air_outer_tag=RegionTag.AIR_OUTER,
            coil_pos_tag=RegionTag.COIL_POS,
            outer_boundary_tag=RegionTag.OUTER_BOUNDARY,
            mu_r_core=inputs.mu_r_core,
            sigma_core_Spm=inputs.sigma_core_Spm,
            sigma_copper_Spm=inputs.sigma_copper_Spm,
            n_turns=inputs.n_turns,
            current_A=inputs.current_A,
            coil_area_m2=inputs.coil_area_m2,
            frequency_Hz=inputs.frequency_Hz,
        )


# ─── Helper: skin-depth check ──────────────────────────────────────


def skin_depth_m(*, frequency_Hz: float, sigma_Spm: float = 5.96e7, mu_r: float = 1.0) -> float:
    """Classical skin depth ``δ = sqrt(2/(ω·σ·μ))`` in metres.

    For copper at 25 °C (σ = 5.96e7 S/m, μ_r = 1):

    f [kHz]   δ [µm]
    ─────────────────
    10        660
    50        295
    100       208
    250       132
    500        93
    1000       66

    Useful to size the mesh in the winding region: at least 2-3
    elements across the skin depth on the surface side.
    """
    import math as _m

    mu0 = 4 * _m.pi * 1e-7
    mu = mu0 * mu_r
    omega = 2 * _m.pi * frequency_Hz
    return _m.sqrt(2.0 / (omega * sigma_Spm * mu))


def recommended_mesh_size_at_skin_m(
    *,
    frequency_Hz: float,
    sigma_Spm: float = 5.96e7,
    mu_r: float = 1.0,
    n_elements_per_skin: int = 3,
) -> float:
    """Mesh size that gives ``n`` elements across one skin depth.

    Default ``n = 3`` is a good compromise between accuracy and
    solver wall time; FEMMT uses similar defaults internally.
    """
    delta = skin_depth_m(frequency_Hz=frequency_Hz, sigma_Spm=sigma_Spm, mu_r=mu_r)
    return delta / max(n_elements_per_skin, 1)


__all__ = [
    "MagnetostaticAcInputs",
    "MagnetostaticAcTemplate",
    "recommended_mesh_size_at_skin_m",
    "skin_depth_m",
]


# Silence unused import warning until Optional is needed.
_ = Optional
