"""Axisymmetric variant of the DC magnetostatic ``.pro`` template.

Same physics as ``magnetostatic.py`` but renders a GetDP file that
uses the **axisymmetric volume jacobian** ``VolAxiSqu`` instead of
the planar ``Vol``. This is the right choice for wound inductors
where the coil produces an azimuthal current density around a
rotation axis — see ``geometry/ei_axi.py`` for the geometric
convention.

Key differences vs the planar template
======================================

1. **Jacobian**: ``VolAxiSqu`` (axisymmetric, "squared" variant
   that includes the extra ``r²`` factor needed by the
   ``A``-formulation). Together with ``SurAxi`` for boundary
   integrals.
2. **Source region**: only ``Coil_pos`` — the axisymmetric
   geometry has a single bobbin around the axis, no "+/−"
   bundle pair like in planar.
3. **No depth scaling in the runner**: GetDP's ``VolAxiSqu``
   integrates ``× 2π·r`` for each element area, so the result
   is already the 3-D revolution integral in J. The runner
   passes ``depth_m = 1.0`` and the energy comes out in J
   directly.
4. **Function space stays the same** (Form1P, BF_PerpendicularEdge):
   the basis represents the azimuthal component of A, which is
   what an axisymmetric wound coil produces.

This matches FEMMT's reference ``solver.pro`` conventions
(``Jacobian VolAxiSqu`` everywhere) — the choice that lets
FEMMT report correct magnitudes on every core shape.
"""

from __future__ import annotations

from pfc_inductor.fea.direct.geometry.base import RegionTag
from pfc_inductor.fea.direct.physics.magnetostatic import MagnetostaticInputs


class MagnetostaticAxiTemplate:
    """Render a GetDP ``.pro`` for the axisymmetric DC magnetostatic."""

    _TEMPLATE = r"""// Auto-generated by pfc_inductor.fea.direct.physics.magnetostatic_axi
// DC magnetostatic — A_φ axisymmetric formulation (r, z plane)
// Inductance via energy: L = 2 · W / I^2

Group {{
  Core       = Region[{core_tag}];
  AirGap     = Region[{air_gap_tag}];
  Air        = Region[{air_outer_tag}];
  Coil_pos   = Region[{coil_pos_tag}];
  OuterBound = Region[{outer_boundary_tag}];

  Magnetic   = Region[ {{Core, AirGap, Air, Coil_pos}} ];
  Source     = Region[ {{Coil_pos}} ];
  NonSource  = Region[ {{Core, AirGap, Air}} ];
}}

Function {{
  mu0       = 4 * Pi * 1e-7;
  mu_r_core = {mu_r_core};
  mu[Core]      = mu0 * mu_r_core;
  mu[AirGap]    = mu0;
  mu[Air]       = mu0;
  mu[Source]    = mu0;
  nu[]          = 1 / mu[];

  // Single coil with azimuthal current density. In an
  // axisymmetric (r, z) model the helix collapses to a single
  // bundle wrapped around the axis; sign is positive by
  // convention.
  N_turns       = {n_turns};
  I_DC          = {current_A};
  A_coil        = {coil_area_m2};
  J_amp         = N_turns * I_DC / A_coil;
  js[Source]    = Vector[ 0, 0, J_amp ];
}}

Constraint {{
  {{ Name MagDirichlet; Type Assign;
     Case {{ {{ Region OuterBound; Value 0.; }} }}
  }}
}}

// Axisymmetric Jacobian: ``VolAxiSqu`` includes the 2π·r factor
// + the extra r² factor required by the A_φ formulation.
Jacobian {{
  {{ Name JVol; Case {{ {{ Region All; Jacobian VolAxiSqu; }} }} }}
  {{ Name JSur; Case {{ {{ Region All; Jacobian SurAxi; }} }} }}
}}

Integration {{
  {{ Name I_Gauss;
     Case {{
       {{ Type Gauss;
          Case {{
            {{ GeoElement Triangle;   NumberOfPoints 4; }}
            {{ GeoElement Quadrangle; NumberOfPoints 4; }}
            {{ GeoElement Line;       NumberOfPoints 4; }}
          }}
       }}
     }}
  }}
}}

FunctionSpace {{
  {{ Name Hcurl_a; Type Form1P;
     BasisFunction {{
       {{ Name se; NameOfCoef ae; Function BF_PerpendicularEdge;
          Support Magnetic; Entity NodesOf[ All ]; }}
     }}
     Constraint {{
       {{ NameOfCoef ae; EntityType NodesOf;
          NameOfConstraint MagDirichlet; }}
     }}
  }}
}}

Formulation {{
  {{ Name Magnetostatic_a; Type FemEquation;
     Quantity {{
       {{ Name a; Type Local; NameOfSpace Hcurl_a; }}
     }}
     Equation {{
       Galerkin {{ [ nu[] * Dof{{d a}} , {{d a}} ];
         In Magnetic; Jacobian JVol; Integration I_Gauss; }}
       Galerkin {{ [ -js[] , {{a}} ];
         In Source; Jacobian JVol; Integration I_Gauss; }}
     }}
  }}
}}

Resolution {{
  {{ Name Magnetostatic;
     System {{ {{ Name Sys_Mag; NameOfFormulation Magnetostatic_a; }} }}
     Operation {{ Generate[Sys_Mag]; Solve[Sys_Mag]; SaveSolution[Sys_Mag]; }}
  }}
}}

PostProcessing {{
  {{ Name Magnetostatic_post; NameOfFormulation Magnetostatic_a;
     Quantity {{
       {{ Name a; Value {{ Local {{ [ {{a}} ]; In Magnetic; Jacobian JVol; }} }} }}
       {{ Name b; Value {{ Local {{ [ {{d a}} ]; In Magnetic; Jacobian JVol; }} }} }}
       {{ Name nrm_b; Value {{ Local {{ [ Norm[{{d a}}] ]; In Magnetic; Jacobian JVol; }} }} }}
       {{ Name w_mag; Value {{ Local {{ [ 0.5 * nu[] * SquNorm[{{d a}}] ];
            In Magnetic; Jacobian JVol; }} }} }}
       // VolAxiSqu integrates × 2π·r, so this Integral already
       // returns the 3-D energy in J — no depth multiplier
       // needed downstream.
       {{ Name W; Value {{ Integral {{ [ 0.5 * nu[] * SquNorm[{{d a}}] ];
            In Magnetic; Jacobian JVol; Integration I_Gauss; }} }} }}
       // Flux-linkage extraction (FEMMT-style). For an axi A_φ
       // formulation, the flux through one turn at radius r is
       // ``Φ(r) = 2π·r·A_φ`` and ``Jacobian VolAxiSqu`` already
       // includes the 2π·r factor. The integral below thus equals
       // ``∫(A_φ × 2π·r)/A_coil dA`` over the bundle, i.e. the
       // "average flux through a turn", scaled by 1/A_coil so the
       // result divided by current yields ``L``.
       //
       // FEMMT's formula: L_nn = ∫ Signn·CoefGeo/AreaCell × CompZ[a] / I_n
       // For us: AreaCell = coil_area_m2 (already 2π·R-corrected),
       //         CoefGeo  = 1 (implicit in VolAxiSqu integration).
       {{ Name FluxLinkageOverI; Value {{ Integral {{
            [ CompZ[{{a}}] / A_coil / I_DC ];
            In Coil_pos; Jacobian JVol; Integration I_Gauss; }} }} }}
     }}
  }}
}}

PostOperation {{
  {{ Name Magnetostatic_out; NameOfPostProcessing Magnetostatic_post;
     Operation {{
       Print[ b,      OnElementsOf Magnetic, File "B_field.pos" ];
       Print[ nrm_b,  OnElementsOf Magnetic, File "Magb.pos" ];
       Print[ w_mag,  OnElementsOf Magnetic, File "loss_density.pos" ];
       Print[ a,      OnElementsOf Magnetic, File "A_potential.pos" ];
       Print[ W[Magnetic], OnGlobal, Format Table, File "energy_2d.txt" ];
       Print[ W[Core],     OnGlobal, Format Table, File "energy_core.txt" ];
       Print[ W[AirGap],   OnGlobal, Format Table, File "energy_gap.txt" ];
       // Flux-linkage / I_DC (FEMMT-style L extraction).
       Print[ FluxLinkageOverI[Coil_pos], OnGlobal, Format Table,
              File "flux_linkage_over_I.txt" ];
     }}
  }}
}}
"""

    def render(self, inputs: MagnetostaticInputs) -> str:
        return self._TEMPLATE.format(
            core_tag=RegionTag.CORE,
            air_gap_tag=RegionTag.AIR_GAP,
            air_outer_tag=RegionTag.AIR_OUTER,
            coil_pos_tag=RegionTag.COIL_POS,
            outer_boundary_tag=RegionTag.OUTER_BOUNDARY,
            mu_r_core=inputs.mu_r_core,
            n_turns=inputs.n_turns,
            current_A=inputs.current_A,
            coil_area_m2=inputs.coil_area_m2,
        )
