"""GetDP magnetostatic ``.pro`` template — DC self-inductance via energy.

Problem statement
=================

Find the magnetic vector-potential ``A`` (z-component only, 2-D
planar) satisfying::

      curl( ν · curl A )  =  J_s        in the source regions
      A = 0                              on the outer boundary
      μ = μ₀ · μ_r(region)               material law

where ``ν = 1/μ`` is the magnetic reluctivity. The right-hand
side ``J_s`` is the imposed current density in the coil regions
(``+J`` in ``COIL_POS``, ``-J`` in ``COIL_NEG``) — corresponds to
``N·I / A_coil`` ampere-turns spread over the bundle area.

Once ``A`` is known we compute:

- Magnetic energy density ``w = ½ · B·H``, integrate over the
  whole 2-D domain → energy per unit depth ``W_2d`` (J/m).
- Multiply by the center-leg depth (``cl_d_m``) to get the
  3-D-equivalent energy ``W`` (J).
- Self-inductance via energy method: ``L = 2·W / I²``.
- Peak ``|B|`` in the core (saturation check).

Why energy method
-----------------

The flux-linkage method (``L = N·Φ / I``) requires either a
"feed-line" cut surface or a counts-of-turns integral inside the
bundle, which is finicky in 2-D when the bundle is homogenized
and ``N`` is not explicitly drawn. The energy method only needs
``A`` and ``J``; works for any winding topology including future
foil / Litz / interleaved layouts.

For a magnetostatic problem with linear materials and a single
exciting coil, the two methods are mathematically identical. We
go with energy because it generalises to nonlinear ``μ(B)`` later
(the analogous "co-energy" formulation drops in cleanly).

Template format
---------------

Plain-text ``.pro`` with Python ``str.format``-style placeholders
filled by :meth:`MagnetostaticTemplate.render`. Keeping the
template inline (instead of a separate ``.pro.tpl`` file) makes
the package self-contained — no resource-loading or
package-data plumbing in the build.
"""

from __future__ import annotations

from dataclasses import dataclass

from pfc_inductor.fea.direct.geometry.base import RegionTag


@dataclass(frozen=True)
class MagnetostaticInputs:
    """Numbers the template substitutes into the rendered ``.pro``.

    All values are in SI units. The template assumes a 2-D planar
    problem; ``depth_m`` is the out-of-plane extrusion length used
    by the postoperation to scale 2-D quantities to 3-D-equivalent.
    """

    mu_r_core: float
    """Relative permeability of the core material (≥ 1). For
    saturation-aware runs this is the small-signal value; the
    full ``μ(B)`` curve goes into a later AC pass."""

    sigma_core_Spm: float = 0.0
    """Core electrical conductivity (S/m). Zero for ferrite (good
    enough for DC magnetostatic); steel laminations get the
    lamination-equivalent ``σ`` later."""

    n_turns: int = 1
    """Total turns of the coil. Used to build the source current
    density: ``J_s = N · I / A_coil``."""

    current_A: float = 1.0
    """DC current through the coil (A). The L extraction is
    independent of this choice (linear problem), but it sets the
    absolute scale of the field plots."""

    coil_area_m2: float = 1e-4
    """Cross-section area of ONE winding bundle (m²) — i.e. the
    area of one window's coil rectangle. Used together with
    ``n_turns × current_A`` to compute the source current density.
    The geometry layer reports this via :class:`CoreGeometry`'s
    result (added in a later refactor; for now the caller passes
    it directly)."""

    depth_m: float = 1e-2
    """Out-of-plane depth — for an EI core this is the center-leg
    depth (``cl_d``). Multiplies 2-D energy → 3-D-equivalent."""


class MagnetostaticTemplate:
    """Render a GetDP ``.pro`` for the DC magnetostatic problem.

    Usage::

        tpl = MagnetostaticTemplate()
        pro_text = tpl.render(
            MagnetostaticInputs(
                mu_r_core=2200,
                n_turns=120,
                current_A=8.0,
                coil_area_m2=2.4e-4,
                depth_m=0.025,
            )
        )
        Path("magnetostatic.pro").write_text(pro_text)
    """

    # The template intentionally keeps region tags as ``str.format``
    # placeholders so the constants in ``geometry/base.RegionTag``
    # are the single source of truth.
    _TEMPLATE = r"""// Auto-generated by pfc_inductor.fea.direct.physics.magnetostatic
// DC magnetostatic — vector-potential formulation A_z (2-D planar)
// Inductance via energy: L = 2 · W / I^2

Group {{
  Core       = Region[{core_tag}];
  AirGap     = Region[{air_gap_tag}];
  Air        = Region[{air_outer_tag}];
  Coil_pos   = Region[{coil_pos_tag}];
  Coil_neg   = Region[{coil_neg_tag}];
  OuterBound = Region[{outer_boundary_tag}];

  // Aggregate regions for the formulation
  Magnetic   = Region[ {{Core, AirGap, Air, Coil_pos, Coil_neg}} ];
  Source_pos = Region[ {{Coil_pos}} ];
  Source_neg = Region[ {{Coil_neg}} ];
  Source     = Region[ {{Source_pos, Source_neg}} ];
  NonSource  = Region[ {{Core, AirGap, Air}} ];
}}

Function {{
  // Permeabilities (μ = μ_0 · μ_r). GetDP wants ν = 1/μ in the
  // weak form, so we provide both for readability.
  mu0       = 4 * Pi * 1e-7;
  mu_r_core = {mu_r_core};
  mu[Core]      = mu0 * mu_r_core;
  mu[AirGap]    = mu0;
  mu[Air]       = mu0;
  mu[Source]    = mu0;     // bobbin air around the coil
  nu[]          = 1 / mu[];

  // Current density in each coil region. RHS sign mirrors the
  // ``+J`` / ``-J`` convention from the geometry layer.
  N_turns       = {n_turns};
  I_DC          = {current_A};
  A_coil        = {coil_area_m2};
  J_amp         = N_turns * I_DC / A_coil;
  js[Source_pos] = Vector[ 0, 0,  J_amp ];
  js[Source_neg] = Vector[ 0, 0, -J_amp ];
}}

Constraint {{
  // Dirichlet ``A_z = 0`` on the outer air-box boundary.
  {{ Name MagDirichlet; Type Assign;
     Case {{ {{ Region OuterBound; Value 0.; }} }}
  }}
}}

// GetDP requires Jacobian + Integration blocks BEFORE the
// FunctionSpace — they're referenced by name in Formulation.
// We use the planar 2-D Jacobian (``Vol`` / ``Sur``) because an
// EI core is genuinely planar — its cross-section is uniform
// along the lamination-stack direction. FEMMT defaults to
// axisymmetric (``VolAxiSqu``) which is right for toroidal /
// pot / PQ but would distort EI geometry. Phase 2 will add
// the axisymmetric variant in a separate ``physics`` template
// when the toroidal geometry generator lands.
Jacobian {{
  {{ Name JVol; Case {{ {{ Region All; Jacobian Vol; }} }} }}
  {{ Name JSur; Case {{ {{ Region All; Jacobian Sur; }} }} }}
}}

Integration {{
  {{ Name I_Gauss;
     Case {{
       {{ Type Gauss;
          Case {{
            {{ GeoElement Triangle;     NumberOfPoints 4; }}
            {{ GeoElement Quadrangle;   NumberOfPoints 4; }}
            {{ GeoElement Line;         NumberOfPoints 4; }}
          }}
       }}
     }}
  }}
}}

FunctionSpace {{
  // 2-D ``A_z`` formulation: a Form1P (1-form perpendicular to
  // the cross-section plane) so that ``{{a}}`` represents the
  // out-of-plane component of the magnetic vector potential and
  // ``{{d a}}`` is its curl = the in-plane magnetic-flux density
  // ``B = (∂A/∂y, -∂A/∂x)``. ``BF_PerpendicularEdge`` is the
  // canonical Whitney-1-form basis attached to MESH NODES for the
  // 2-D planar case (it's the basis FEMMT uses, and the GetDP
  // book uses for its ``MagSta_a_2D`` reference formulation).
  // The earlier Form0 + BF_Node combo we shipped in Phase 1.0
  // compiled cleanly but gave L_dc that was constant in μ_r —
  // GetDP was using the wrong constitutive law internally.
  {{ Name Hcurl_a; Type Form1P;
     BasisFunction {{
       {{ Name se; NameOfCoef ae; Function BF_PerpendicularEdge;
          Support Magnetic; Entity NodesOf[ All ]; }}
     }}
     Constraint {{
       {{ NameOfCoef ae; EntityType NodesOf;
          NameOfConstraint MagDirichlet; }}
     }}
  }}
}}

Formulation {{
  {{ Name Magnetostatic_a; Type FemEquation;
     Quantity {{
       {{ Name a; Type Local; NameOfSpace Hcurl_a; }}
     }}
     Equation {{
       // Weak form for the 2-D A_z formulation with Form1P.
       // Source split across two explicit Galerkin terms (one per
       // sub-region) so GetDP resolves ``js[r]`` against the local
       // region rather than the union — the union form
       // ``In Source`` was producing a numerically-small RHS in
       // testing, possibly because ``js[]`` lookups for a union
       // region fall through to the per-region definitions in
       // unpredictable order.
       Galerkin {{ [ nu[] * Dof{{d a}} , {{d a}} ];
         In Magnetic; Jacobian JVol; Integration I_Gauss; }}
       Galerkin {{ [ -js[] , {{a}} ];
         In Coil_pos; Jacobian JVol; Integration I_Gauss; }}
       Galerkin {{ [ -js[] , {{a}} ];
         In Coil_neg; Jacobian JVol; Integration I_Gauss; }}
     }}
  }}
}}

Resolution {{
  {{ Name Magnetostatic;
     System {{ {{ Name Sys_Mag; NameOfFormulation Magnetostatic_a; }} }}
     Operation {{ Generate[Sys_Mag]; Solve[Sys_Mag]; SaveSolution[Sys_Mag]; }}
  }}
}}

PostProcessing {{
  {{ Name Magnetostatic_post; NameOfFormulation Magnetostatic_a;
     Quantity {{
       // a = A_z scalar; B = curl(A_z·ẑ) lives in the (x,y) plane
       // and ``{{d a}}`` gives that 2-D rotation directly in GetDP
       // for a Form0 quantity. ``Norm[{{d a}}]`` is |B|.
       {{ Name a; Value {{ Local {{ [ {{a}} ]; In Magnetic; Jacobian JVol; }} }} }}
       {{ Name b; Value {{ Local {{ [ {{d a}} ];
            In Magnetic; Jacobian JVol; }} }} }}
       {{ Name h; Value {{ Local {{ [ nu[] * {{d a}} ];
            In Magnetic; Jacobian JVol; }} }} }}
       {{ Name nrm_b; Value {{ Local {{ [ Norm[{{d a}}] ];
            In Magnetic; Jacobian JVol; }} }} }}
       // Energy density w = ½ · ν · |B|².
       {{ Name w_mag; Value {{ Local {{ [ 0.5 * nu[] * SquNorm[{{d a}}] ];
            In Magnetic; Jacobian JVol; }} }} }}
       // Volume-integrated energy per unit depth (2-D problem).
       {{ Name W_2d; Value {{ Integral {{ [ 0.5 * nu[] * SquNorm[{{d a}}] ];
            In Magnetic; Jacobian JVol; Integration I_Gauss; }} }} }}
     }}
  }}
}}

PostOperation {{
  {{ Name Magnetostatic_out; NameOfPostProcessing Magnetostatic_post;
     Operation {{
       // Field plots — one .pos file per quantity, ready for the
       // pos_renderer to convert to matplotlib PNGs.
       Print[ b,      OnElementsOf Magnetic, File "B_field.pos" ];
       Print[ h,      OnElementsOf Magnetic, File "H_field.pos" ];
       Print[ nrm_b,  OnElementsOf Magnetic, File "Magb.pos" ];
       Print[ w_mag,  OnElementsOf Magnetic, File "loss_density.pos" ];
       Print[ a,      OnElementsOf Magnetic, File "A_potential.pos" ];

       // Scalars — energy per unit depth. The runner multiplies
       // by ``depth_m`` and computes L = 2 W / I^2 in Python.
       Print[ W_2d[Magnetic],    OnGlobal, Format Table, File "energy_2d.txt" ];
       Print[ W_2d[Core],        OnGlobal, Format Table, File "energy_core.txt" ];
       Print[ W_2d[AirGap],      OnGlobal, Format Table, File "energy_gap.txt" ];
     }}
  }}
}}
"""

    def render(self, inputs: MagnetostaticInputs) -> str:
        """Substitute ``inputs`` into the template and return the
        rendered ``.pro`` source ready to write to disk.
        """
        return self._TEMPLATE.format(
            core_tag=RegionTag.CORE,
            air_gap_tag=RegionTag.AIR_GAP,
            air_outer_tag=RegionTag.AIR_OUTER,
            coil_pos_tag=RegionTag.COIL_POS,
            coil_neg_tag=RegionTag.COIL_NEG,
            outer_boundary_tag=RegionTag.OUTER_BOUNDARY,
            mu_r_core=inputs.mu_r_core,
            n_turns=inputs.n_turns,
            current_A=inputs.current_A,
            coil_area_m2=inputs.coil_area_m2,
        )
