"""DC magnetostatic with circuit-coupled bundle (GlobalQuantity).

Phase 1.4 of the FEMMT migration. Replaces the constant-``J`` source
in ``magnetostatic.py`` with a **global current DOF** that the
solver pins via a ``Constraint Current_2D`` external boundary
condition. This matches FEMMT's reference ``solver.pro`` and is
the structural piece that recovers the wound-coil flux-linkage
that distributed-``J`` formulations miss (see ``PHASE_1_4_PLAN.md``
for the diagnostic chain that led here).

Key additions vs ``magnetostatic.py``
=====================================

1. **New function space ``Hregion_i_2D``** (Type Vector,
   BF_RegionZ basis) — represents the bundle's total current
   as a single global DOF ``ir``, region-wise constant across
   ``Coil_pos``.
2. **GlobalQuantity declarations** ``Is`` / ``Us`` aliased to
   ``ir`` (Is) and associated with it (Us). External current
   pinned via the ``Current_2D`` constraint; ``Us`` is
   solved by the system.
3. **Source term via DOF** ``-1/AreaCell · Dof{ir}·{a}``
   instead of the previous ``-CompZ[js[]]·{a}``. Mathematically
   equivalent for fixed I but lets GetDP treat the current as
   a system unknown rather than a constant — which is what
   FEMMT does, and what fixes the 100× magnitude gap on the
   wound-coil case.
4. **GlobalTerm** ``Dof{Us}·{Is}`` — the global circuit
   equation that closes the system.

Inductance extraction
---------------------

We keep the energy method ``L = 2W/I²`` for the DC pass. AC
extraction via ``L = Im(Us)/(ω·Is)`` is Phase 2 territory.
"""

from __future__ import annotations

from pfc_inductor.fea.direct.geometry.base import RegionTag
from pfc_inductor.fea.direct.physics.magnetostatic import MagnetostaticInputs


class MagnetostaticGlobalQTemplate:
    """Render a GetDP ``.pro`` with circuit-coupled bundle DOF."""

    _TEMPLATE = r"""// Auto-generated by pfc_inductor.fea.direct.physics.magnetostatic_globalq
// DC magnetostatic — circuit-coupled bundle (Hregion_i_2D + GlobalQuantity)
// Phase 1.4 of the FEMMT migration

Group {{
  Core       = Region[{core_tag}];
  AirGap     = Region[{air_gap_tag}];
  Air        = Region[{air_outer_tag}];
  Coil_pos   = Region[{coil_pos_tag}];
  Coil_neg   = Region[{coil_neg_tag}];
  OuterBound = Region[{outer_boundary_tag}];

  Magnetic   = Region[ {{Core, AirGap, Air, Coil_pos, Coil_neg}} ];
  Source     = Region[ {{Coil_pos, Coil_neg}} ];
}}

Function {{
  mu0       = 4 * Pi * 1e-7;
  mu_r_core = {mu_r_core};
  mu[Core]      = mu0 * mu_r_core;
  mu[AirGap]    = mu0;
  mu[Air]       = mu0;
  mu[Source]    = mu0;
  nu[]          = 1 / mu[];

  N_turns       = {n_turns};
  I_DC          = {current_A};
  // ``AreaCell`` is the bundle 2-D cross-section area. FEMMT
  // uses it as the per-strand area; for our homogenised single-
  // bundle source we use the full bundle area, which is
  // mathematically equivalent to FEMMT's per-strand × N_strands.
  AreaCell[Coil_pos] = {coil_area_m2};
  AreaCell[Coil_neg] = {coil_area_m2};
}}

Constraint {{
  {{ Name MagDirichlet; Type Assign;
     Case {{ {{ Region OuterBound; Value 0.; }} }}
  }}
  // External current pin: the GlobalQuantity ``Is`` for the
  // bundle is forced to N·I (total ampere-turns). FEMMT names
  // this ``Current_2D`` — we follow.
  {{ Name Current_2D; Type Assign;
     Case {{
       {{ Region Coil_pos; Value (N_turns * I_DC); }}
       {{ Region Coil_neg; Value (-N_turns * I_DC); }}
     }}
  }}
  // Voltage is unconstrained — solved by the system. The empty
  // Case is the GetDP idiom for "no constraint, leave free".
  {{ Name Voltage_2D; Type Assign; Case {{ }} }}
}}

Jacobian {{
  {{ Name JVol; Case {{ {{ Region All; Jacobian Vol; }} }} }}
  {{ Name JSur; Case {{ {{ Region All; Jacobian Sur; }} }} }}
}}

Integration {{
  {{ Name I_Gauss;
     Case {{
       {{ Type Gauss;
          Case {{
            {{ GeoElement Triangle;   NumberOfPoints 4; }}
            {{ GeoElement Quadrangle; NumberOfPoints 4; }}
            {{ GeoElement Line;       NumberOfPoints 4; }}
          }}
       }}
     }}
  }}
}}

FunctionSpace {{
  // A_z vector potential, same as the simple template.
  {{ Name Hcurl_a; Type Form1P;
     BasisFunction {{
       {{ Name se; NameOfCoef ae; Function BF_PerpendicularEdge;
          Support Magnetic; Entity NodesOf[ All ]; }}
     }}
     Constraint {{
       {{ NameOfCoef ae; EntityType NodesOf;
          NameOfConstraint MagDirichlet; }}
     }}
  }}

  // Bundle-current DOF — region-wise constant Vector. ``ir`` is
  // the local coefficient; ``Is`` and ``Us`` are the global
  // quantities accessible to the Formulation as ``Type Global``.
  {{ Name Hregion_i_2D; Type Vector;
     BasisFunction {{
       {{ Name sr; NameOfCoef ir; Function BF_RegionZ;
          Support Source; Entity Source; }}
     }}
     GlobalQuantity {{
       {{ Name Is; Type AliasOf;        NameOfCoef ir; }}
       {{ Name Us; Type AssociatedWith; NameOfCoef ir; }}
     }}
     Constraint {{
       {{ NameOfCoef Us; EntityType Region; NameOfConstraint Voltage_2D; }}
       {{ NameOfCoef Is; EntityType Region; NameOfConstraint Current_2D; }}
     }}
  }}
}}

Formulation {{
  {{ Name Magnetostatic_a; Type FemEquation;
     Quantity {{
       {{ Name a;  Type Local;  NameOfSpace Hcurl_a; }}
       // Local current-density DOF and its globals.
       {{ Name ir; Type Local;  NameOfSpace Hregion_i_2D; }}
       {{ Name Us; Type Global; NameOfSpace Hregion_i_2D[Us]; }}
       {{ Name Is; Type Global; NameOfSpace Hregion_i_2D[Is]; }}
     }}
     Equation {{
       // Stiffness — same as before.
       Galerkin {{ [ nu[] * Dof{{d a}} , {{d a}} ];
         In Magnetic; Jacobian JVol; Integration I_Gauss; }}

       // Source via Dof{{ir}} (circuit-coupled). FEMMT uses
       // ``-1/AreaCell × Dof{{ir}}`` paired directly with ``{{a}}`` —
       // ``ir`` is a Vector DOF whose z-component is the bundle
       // current. GetDP handles the projection against the
       // Form1P test function internally.
       Galerkin {{ [ -1/AreaCell[] * Dof{{ir}} , {{a}} ];
         In Source; Jacobian JVol; Integration I_Gauss; }}

       // Global circuit equation: Dof{{Us}} × {{Is}} — pins Us as
       // the unknown the constraint Is = Current_2D drives.
       GlobalTerm {{ [ Dof{{Us}} , {{Is}} ]; In Source; }}
     }}
  }}
}}

Resolution {{
  {{ Name Magnetostatic;
     System {{ {{ Name Sys_Mag; NameOfFormulation Magnetostatic_a; }} }}
     Operation {{ Generate[Sys_Mag]; Solve[Sys_Mag]; SaveSolution[Sys_Mag]; }}
  }}
}}

PostProcessing {{
  {{ Name Magnetostatic_post; NameOfFormulation Magnetostatic_a;
     Quantity {{
       {{ Name a; Value {{ Local {{ [ {{a}} ]; In Magnetic; Jacobian JVol; }} }} }}
       {{ Name b; Value {{ Local {{ [ {{d a}} ]; In Magnetic; Jacobian JVol; }} }} }}
       {{ Name nrm_b; Value {{ Local {{ [ Norm[{{d a}}] ];
            In Magnetic; Jacobian JVol; }} }} }}
       {{ Name w_mag; Value {{ Local {{ [ 0.5 * nu[] * SquNorm[{{d a}}] ];
            In Magnetic; Jacobian JVol; }} }} }}
       {{ Name W_2d; Value {{ Integral {{ [ 0.5 * nu[] * SquNorm[{{d a}}] ];
            In Magnetic; Jacobian JVol; Integration I_Gauss; }} }} }}
       // Diagnostic: integrated source current and voltage.
       {{ Name I_global; Value {{ Term {{ [ {{Is}} ]; In Source; }} }} }}
       {{ Name U_global; Value {{ Term {{ [ {{Us}} ]; In Source; }} }} }}
     }}
  }}
}}

PostOperation {{
  {{ Name Magnetostatic_out; NameOfPostProcessing Magnetostatic_post;
     Operation {{
       Print[ b,      OnElementsOf Magnetic, File "B_field.pos" ];
       Print[ nrm_b,  OnElementsOf Magnetic, File "Magb.pos" ];
       Print[ w_mag,  OnElementsOf Magnetic, File "loss_density.pos" ];
       Print[ a,      OnElementsOf Magnetic, File "A_potential.pos" ];
       Print[ W_2d[Magnetic], OnGlobal, Format Table, File "energy_2d.txt" ];
       Print[ W_2d[Core],     OnGlobal, Format Table, File "energy_core.txt" ];
       Print[ W_2d[AirGap],   OnGlobal, Format Table, File "energy_gap.txt" ];
     }}
  }}
}}
"""

    def render(self, inputs: MagnetostaticInputs) -> str:
        return self._TEMPLATE.format(
            core_tag=RegionTag.CORE,
            air_gap_tag=RegionTag.AIR_GAP,
            air_outer_tag=RegionTag.AIR_OUTER,
            coil_pos_tag=RegionTag.COIL_POS,
            coil_neg_tag=RegionTag.COIL_NEG,
            outer_boundary_tag=RegionTag.OUTER_BOUNDARY,
            mu_r_core=inputs.mu_r_core,
            n_turns=inputs.n_turns,
            current_A=inputs.current_A,
            coil_area_m2=inputs.coil_area_m2,
        )
